buildscript {
    dependencies {
        classpath(fileTree(dir: "${gradle.gradleUserHomeDir}/caches/modules-2/files-2.1", include: ['**/*.jar']))
    }
}

plugins {
	id 'maven-publish'
}

apply plugin: 'fabric-loom'

sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21

archivesBaseName = project.archives_base_name
version = project.mod_version
group = project.maven_group

repositories {
}

loom {
	accessWidenerPath = file("src/main/resources/rebind_all_the_keys.accesswidener")
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-key-binding-api-v1:1.0.47+0af3f5a76a"
	modImplementation "net.fabricmc.fabric-api:fabric-lifecycle-events-v1:2.3.12+6c1df3606a"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 21
}

java {
	withSourcesJar()
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archivesBaseName}"}
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}
}
